music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [
	#/music/
    url(r'^$', views.index, name='index'),

    #/music/album_id
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name= 'details' ),

    #/music/album_id/favorite
	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name= 'favorite' )    
	    

	    

]

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
     
]

music/models.py
from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length= 250)
	album_title = models.CharField(max_length= 500)
	genre = models.CharField(max_length= 300)
	album_logo = models.CharField(max_length= 1000)

	def __str__(self):
		return self.artist + ' - ' + self.album_title  


class Songs(models.Model):
	album= models.ForeignKey(Album, on_delete= models.CASCADE)
	file_type= models.CharField(max_length= 10)
	song_title= models.CharField(max_length= 250)
	is_favorite= models.BooleanField(default= False) 
 
	def __str__(self):
		return self.song_title

music/views.py
#from django.http import HttpResponse
from django.http import Http404
#from django.template import loader
#shortcut of above 
from django.shortcuts import render, get_object_or_404
from models import Album, Songs

def index(request):
	all_albums= Album.objects.all()	
	context= {'all_albums': all_albums }
	return render(request, "music/index.html", context)
	#it covers Httprespose too.
	


def details(request, album_id):
	album= Album.objects.get(pk=album_id)
	'''try:
		album= Album.objects.get(pk=album_id)
	except Album.DoesNotExist:
		raise Http404("Album Does Not Exist")'''
	# We can directly do
	album= get_object_or_404(Album, pk=album_id)

	return render(request, "music/detail.html", {'album':album})


def favorite(request, album_id ):
	album= Album.objects.get(pk=album_id)
	try:
		selected_song= album.songs_set.get(pk=request.POST['song'])
	except(KeyError , Songs,DoesNotExist):
		return 	render(request, "music/detail.html", {'album':album, 'error_message':"You Did Not Selected A Valid Song"})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return 	render(request, "music/detail.html", {'album':album})

music/templates/music/detail.html
<img src= "{{album.album_logo}}"/>

<h1> {{album.album_title}} </h1>
<h2> {{album.artist}} :</h2>

<!--<u1>
	{% for song in album.songs_set.all %}
		<li> {{song.song_title}} - {{song.file_type}} </li>
	{% endfor %}
</u1> -->

{% if error_message%}
	<p><strong> {{error_message}} </strong></p>	
{%endif%}



<form action= "{% url 'music:favorite' album.id %}"  method= "post"> 
	{%csrf_token %}
	{% for song in album.songs_set.all %}
		<input type = "radio" id="song{{ forloop.counter}}" name= "song" value= {{song.id}} >
		<label for="song{{ forloop.counter}} "> 
			{{song.song_title}} - {{song.file_type}}
			{% if song.is_favorite %}
				<img src= "https://wiki.ceh.ac.uk/s/en_GB/3398/84f448c1067609161db7eeaf020f96b084eef29d.11/_/images/icons/emoticons/star_blue.png"/>

			{%endif%}
		</label><br>
	{%endfor%}
	<input type= "submit" value= "Favorite" >
</form>

music/templates/music/index.html
{% if all_albums %}

	<h2> Here are all my Albums </h2>
	<ul>

	{% for album in all_albums %}
	<li><a href = "{% url 'music:details' album.id %}" ><strong>{{album.album_title}}</strong></a></li>
	{% endfor %}
	</ul>

{% else %}
	<h3> You Dont Have Album To show</h3>

{% endif %}